# Generated by Django 4.1.5 on 2023-01-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=150)),
                ('dia', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
