# Generated by Django 4.1.5 on 2023-01-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycrud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefas',
            name='dia',
            field=models.CharField(max_length=10),
        ),
    ]
